 const resources = {
    en: {
      translation: {
        app_name: "Jumia",
        help: 'help',
        lang: 'language',
        top_search: 'Search for products',
        offical: 'Offical stores',
        jumiaDoniation: 'Jumia Doniation',
        orangePoints: 'Orange Points',

        superMarket: 'Supermarket products',
        fashion: 'Fashions products',
        PhonesTablets: 'Phones & Tablets products',
        homeOffice: 'Home & Office products',
        electroic: 'Electronics products',


        newToJuima: 'NEW TO JUMIA?',
        subcsribeMesg: 'Subscribe to our newsletter to get updates on our latest offers!',
        downloadJumi: 'DOWNLOAD JUMIA FREE APP',
        getAccess: 'Get access to exclusive offers!',
        letUsHelpU: 'LET US HELP YOU',
        helpCenter: 'Help center',
        contactUs: 'Contact Us',
        privacy: 'Privacy',
        shipDP: 'Shipping & Delivery Policy',
        termsAndCondtion: 'Terms and Conditions',
        reportAPro: 'Report a product',
        joinUs: 'JOIN US ON',
        aboutJumiaEgypt: 'ABOUT JUMIA EGYPT',
        howToPy: 'How to pay on Jumia?',
        returnPolicy: 'Return Policy',
        makeMoeny: 'MAKE MONEY WITH JUMIA',
        sellOnJumia: 'Sell on Jumia',
        jumiaInterNational: 'JUMIA INTERNATIONAL',
        Algeria: 'Algeria',
        Ghana: 'Ghana',
        Kenya: 'Kenya',
        Morocco: 'Morocco',
      },
    },
    ar: {
      translation: {
        app_name: "جوميا",
        help: 'المساعدة',
        lang: 'اللغة',
        top_search: 'البحث عن المنتجات',
        offical: 'المتاجر الرسمية',
        jumiaDoniation: 'التبرعات',
        orangePoints: 'نقاط Orange',

        superMarket: 'منتجات السوبرماركت',
        fashion: 'منتجات الموضة',
        PhonesTablets: 'منتجات الموبايل والتابلت',
        homeOffice: 'منتجات المكاتب',
        electroic: 'المنتجات الإلكترونية',

        newToJuima: 'مستخدم جديد لدي جوميا؟',
        subcsribeMesg: 'إشترك في نشرتنا البريدبة وإحصل علي آخر العروض والتحديثات.',
        downloadJumi: 'قم بتحميل التطبيق',
        getAccess: 'إحصل علي العروض الحصرية',
        letUsHelpU: 'دعنا نساعدك',
        helpCenter: 'مركز المساعدة',
        contactUs: 'إتصل بنا',
        privacy: 'سياسة الخصوصية',
        shipDP: 'سياسة التوصيل',
        termsAndCondtion: 'إتفاقية الإستخدام',
        reportAPro: 'الإبلاغ عن مشكلة',
        joinUs: 'إنضم إلينا',
        aboutJumiaEgypt: 'عن جوميا مصر',
        howToPy: 'كيفية الدفع علي جوميا',
        returnPolicy: 'سياسة الإسترجاع',
        makeMoeny: 'العمل مع جوميا بالعمولة',
        sellOnJumia: 'البيع علي جوميا',
        jumiaInterNational: 'جوميا الدولي',
        Algeria: 'الجزائر',
        Ghana: 'غانا',
        Kenya: 'كينيا',
        Morocco: 'المغرب',

      },
    },
  };

  export default resources;